//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.12.10 at 03:23:46 PM GMT 
//


package ie.gmit.sw.DataModel;

import java.io.Serializable;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Booking_id" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="NameOfCar" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="NoOfDays" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "bookingId",
    "nameOfCar",
    "noOfDays"
})
@XmlRootElement(name = "booking")
public class Booking implements Serializable{

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	@XmlElement(name = "Booking_id")
    protected int bookingId;
    @XmlElement(name = "NameOfCar", required = true)
    protected String nameOfCar;
    @XmlElement(name = "NoOfDays")
    protected int noOfDays;
    
    
    public Booking() {
    	super();
    }

    public Booking(int bookingId, String nameOfCar, int noOfDays) {
		super();
		this.bookingId = bookingId;
		this.nameOfCar = nameOfCar;
		this.noOfDays = noOfDays;
	}

	/**
     * Gets the value of the bookingId property.
     * 
     */
    public int getBookingId() {
        return bookingId;
    }

    /**
     * Sets the value of the bookingId property.
     * 
     */
    public void setBookingId(int value) {
        this.bookingId = value;
    }

    /**
     * Gets the value of the nameOfCar property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNameOfCar() {
        return nameOfCar;
    }

    /**
     * Sets the value of the nameOfCar property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNameOfCar(String value) {
        this.nameOfCar = value;
    }

    /**
     * Gets the value of the noOfDays property.
     * 
     */
    public int getNoOfDays() {
        return noOfDays;
    }

    /**
     * Sets the value of the noOfDays property.
     * 
     */
    public void setNoOfDays(int value) {
        this.noOfDays = value;
    }

}
